<?php

/**
 * @file
 * Hook implementations for the count_up module.
 */

/**
 * Implements hook_field_widget_form_alter().
 */
function count_up_field_widget_form_alter(&$element, &$form_state, $context) {
  if ($context['field']['field_name'] != 'count_up') {
    return;
  }

  $visibility_id = drupal_html_id('count_up-visibility');
  $visibility_state['#states']['visible']["#$visibility_id"]['checked'] = TRUE;
  $element['count_up_visibility']['und']['#id'] = $visibility_id;

  foreach (element_children($element) as $key) {
    if ($key != 'count_up_visibility') {
      $element[$key] += $visibility_state;
    }
  }
  $element['count_up_initial_time'][LANGUAGE_NONE][0]['#count_up_container'] = TRUE;
  $element['#attributes']['class'][] = 'field-group-heading';
}

/**
 * Implements hook_date_combo_process_alter().
 *
 * Render our datetime elements as containers.
 */
function count_up_date_combo_process_alter(&$element, $form_state, $context) {
  if (!empty($element['#count_up_container'])) {
    $element['#theme_wrappers'] = ['container'];
    $element['value'] += [
      '#title' => $element['#title'],
    ];
  }
}
